### PR TITLE
Fixed: Yith Conflict - Add to wishlist button does not show up for vendor roles. #707

### LINKED ISSUE #707: Yith Conflict - Add to wishlist button does not show up for vendor roles.
**Describe the bug**
The problem was the "add to wishlist" button shows up ok for logged out users and for logged in users with the role of Admin and Customer.
However the button does not show up when a user with the role of Vendor is logged in.

Yith mentioned this from their reply:
The main problem is that this plugin is using the product_type_selector filter (http://hookr.io/filters/product_type_selector/) to include the styles from the above option. If you open the class-admin-users.php and search for the filter_product_types method, you will see the following:
Selección_018

**To Reproduce**
1. Log in as a customer/other role
2. Check a single product page and see the "Add to wishlist" Button
3. Notice that if you are logged in as a vendor, this will not show.

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by mahlamusa**
### All Submissions:

* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #707 .

### How to test the changes in this Pull Request:

1.  Log in as a customer/another role
2. Check a single product page and see the "Add to wishlist" Button
3. The 'Add to wishlist" button must be visible when logged in as Customer/Vendor/Administrator or any other role.
4. If the product is already on the wishlist, the appropriate message must be visible when logged in as Customer/Vendor/Administrator or any other role

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### CODE REVIEW

File: classes/admin/class-admin-users.php [hunk 1]
```diff
@@ -180,10 +180,6 @@ function filter_product_types( $types ) {
 			}
 		}
 
-		echo '<style>';
```
Comment (ketulsheth85) [inline classes/admin/class-admin-users.php:183]: By removing this all the advanced stylesheets are removed.

**Review by ketulsheth85 — CHANGES_REQUESTED** [review]
By removing this all the advanced stylesheets are removed.

**Review by digitalchild — COMMENTED** [review]
Move the styles into its own wp_enqueue_style call.

**Review by digitalchild — APPROVED** [review]

**Review by ketulsheth85 — APPROVED** [review]
