### PR TITLE
Fixed: Order total incorrect in vendor order emails when coupon is used #726

### LINKED ISSUE #726: Order total incorrect in vendor order emails when coupon is used
**Describe the bug**

As checked, when a customer creates an order using a coupon, in this example, 100%, the total is still displaying the full amount of the total price - https://share.getcloudapp.com/d5upB7yj

Product Total should now be displayed as $0.00, this would make sure that the vendor would not make expectation that they should receive a commission as the vendor coupon was used for the purchase.

**To Reproduce**
1.) create a vendor coupon
2.) Use it for an order
3.) see the product total

**Screenshots**
https://share.getcloudapp.com/d5upB7yj
 - There's also nothing for the new-order mail that says the customer used the coupon.

**Expected behavior**
Product total should be 0 as well.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WC Vendors and WooCommerce are active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

### PR DESCRIPTION
**Pull request by ketulsheth85**
### All Submissions:

* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

Closes #726 .

### How to test the changes in this Pull Request:

1.) create a vendor coupon
2.) Use it for an order
3.) see the product total

### CODE REVIEW

**Review by digitalchild — COMMENTED** [review]
We have options in the email that allows the marketplace admin to show the totals display with the commission or product, or both commission and product or no totals. We need to ensure that this is still being output as we have a lot of marketplaces that only show the commission totals or the product totals.

File: classes/includes/wcv-template-functions.php [hunk 1]
```diff
@@ -83,6 +83,7 @@ function wcv_get_vendor_item_totals( $order, $items, $vendor_id, $email, $totals
 		$shipping            = 0;
 		$total               = 0;
 		$total_rows          = array();
+		$discount 			 = $order->get_total_discount();
```
Comment (digitalchild) [inline classes/includes/wcv-template-functions.php:86]: This would get the total discounts from all vendors, not the particular vendor. resulting in the amounts not being correct. Need to check what the coupon was, who owns it and then determine the coupon discount amount.

**Review by digitalchild — CHANGES_REQUESTED** [review]
The values are not changing in the email contents with these changes.

**Review by mahlamusa — APPROVED** [review]

**Review by digitalchild — APPROVED** [review]
