### PR TITLE
Fixed: Timezone display for commissions #625

### LINKED ISSUE #625: Timezone display for commissions
**Describe the bug**

This is the first time it has been reported and we are unable to properly determine if this is related to the customer's environment or not. 

If a different timezone is set in the Settings > General then the time set in the database uses the server time not the time used in the settings. 

> I was able to duplicate the issue on the staging site. I just simply created a new order in woocommerce. The product is associated with a vendor to receive commissions. I marked the order as complete, which generated the commission. The order date is 2/5/20 and the commission date is showing 2/6/20

Commissions are stored in the database using `$order->get_date_created()` then we store it with the following -` date( 'Y-m-d H:i:s', strtotime( $order_date ).`

Need to confirm that the timezone display is actually an issue or not. If it is, we should only change the display of the date, not the stored date in the commission's table. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Settings > General - change the timezone to somewhere other than the server time. 
2. Process order and complete it. 
3. Check that the order time in WC Vendors > commission
4. The commission is off compared to the woocommerce order date 

**Screenshots**
image001

In this screenshot the last_updated column is added by another plugin and uses mysql date function to trigger the storage with the correct date. 

**Expected behaviour**
The order date and the commission dates should be the displaying as the same date.

### PR DESCRIPTION
**Pull request by mahlamusa**
### All Submissions:

* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Use gmdate() to avoid runtime errors associated with date() function.

Closes #625 

### How to test the changes in this Pull Request:

1. Go to Settings > General - change the timezone to somewhere other than the server time.
2. Process order and complete it.
3. Check that the order time in WC Vendors > commission
4. The commission date must be the same as the WooCommerce order date

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

### CODE REVIEW

File: classes/class-commission.php [hunk 1]
```diff
@@ -171,7 +171,7 @@ public static function log_commission_due( $order_id ) {
 					'total_shipping' => ! empty( $insert_due[ $product_id ]['total_shipping'] ) ? ( $detail['shipping'] + $insert_due[ $product_id ]['total_shipping'] ) : $detail['shipping'],
 					'tax'            => ! empty( $insert_due[ $product_id ]['tax'] ) ? ( $detail['tax'] + $insert_due[ $product_id ]['tax'] ) : $detail['tax'],
 					'qty'            => ! empty( $insert_due[ $product_id ]['qty'] ) ? ( $detail['qty'] + $insert_due[ $product_id ]['qty'] ) : $detail['qty'],
-					'time'           => date( 'Y-m-d H:i:s', strtotime( $order_date ) ),
+					'time'           => gmdate( 'Y-m-d H:i:s', strtotime( $order_date ) ),
```
Comment (digitalchild) [inline classes/class-commission.php:174]: How will this effect existing commissions? Will this slide the commission times between old and new commissions?
