### PR TITLE
Fixed: Errors in order template #757

### LINKED ISSUE #757: Errors in order template
1.
(84) new WC_Product( $value['product_id'] );
This does not work properly for product types other then 'simple'. Use wc_get_product( $value['product_id'] ); instead.
2.
(85) $needs_shipping = ( ! $product->needs_shipping() || $product->is_downloadable( 'yes' ) ) ? false : true;
This looses state of $needs_shipping if multiple products are in order. This causes the "Mark Shipped" option unavailable if the order is a mix of shipable and virtual products. Use 
$needs_shipping = ( ! $product->needs_shipping() || $product->is_downloadable( 'yes' ) ) ? $needs_shipping : true;
instead.
3.
(79)-(87) The for loop loops over all products in the order, not just the ones that belong to the current vendor. The $needs_shipping variable gets updated for other vendor's products, which is wrong. The if statement should end together with the for loop like this:

foreach ( $items as $key => $value ) {
				if ( in_array( $value['variation_id'], $valid_items ) || in_array( $value['product_id'], $valid_items ) ) {
					$valid[] = $value;
				
				// See if product needs shipping
				$product        = wc_get_product( $value['product_id'] );
				$needs_shipping = ( ! $product->needs_shipping() || $product->is_downloadable( 'yes' ) ) ? $needs_shipping : true;
                }
			}

### PR DESCRIPTION
**Pull request by ketulsheth85**
### All Submissions:

* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

Closes #757 .

### How to test the changes in this Pull Request:

1. Change WC_Product to use wc_get_product.
2. Needs shipping state consistency.

### CODE REVIEW

File: templates/dashboard/orders.php [hunk 1]
```diff
@@ -79,11 +79,10 @@
 			foreach ( $items as $key => $value ) {
 				if ( in_array( $value['variation_id'], $valid_items ) || in_array( $value['product_id'], $valid_items ) ) {
```
Comment (Mrlunsuper) [inline templates/dashboard/orders.php:80]: Should we set the third parameter to true to force the use of strict comparison for in_array?

Comment (digitalchild) [reply templates/dashboard/orders.php:80]: @Mrlunsuper We currently don't force strict comparison, but if you can provide a good reason for this. Lets start a discussion around this on slack.

**Review by digitalchild — APPROVED** [review]
